language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install libgsl0ldbl
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-python-dev
  - cd include 
  - make
  - cd ..
install:
  - python setup.py install

script:
  - python -m unittest unit_test.py
  - python example_pf.py
