os: osx
before_install:
  - brew install gsl
  - brew install boost-python
  - cd include 
  - make
  - cd ..
install:
  - python setup.py install

script:
  - python -m unittest unit_test.py
  - python example_pf.py
