os: 
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl boost-python; fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-all-dev libgsl0-dev libgsl0ldbl; fi 
  - cd include 
  - make
  - cd ..
install:
  - python setup.py install

script:
  - python -m unittest unit_test
  - python example_pf.py
