os: 
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_oS_NAME" == "osx" ]]; then 
      brew install gsl,boost-python; 
    else
      sudo apt-get install libgsl0-dev,libgsl0ldbl,libboost-all-dev; 
    fi
  - cd include 
  - make
  - cd ..
install:
  - python setup.py install

script:
  - python -m unittest unit_test
  - python example_pf.py
