os: osx
language: python
python:
  - "3.6"
before_install:
  - brew install gsl
  - brew install boost-python3
  - cd include 
  - make
  - cd ..
install:
  - python setup.py install

script:
  - python -m unittest unit_test.py
  - python example_pf.py
