version: 1.0.{build}
init:
- cmd: set CONDA_PREFIX=C:\Miniconda-x64
install:
- cmd: >-
    %CONDA_PREFIX%\Scripts\conda install --yes -c conda-forge gsl

    %CONDA_PREFIX%\Scripts\conda install --yes -c conda-forge boost

    copy boost_python_config_patch.hpp %CONDA_PREFIX%\Library\include\boost\python\detail\config.hpp

build_script:
- cmd: %CONDA_PREFIX%\python.exe setup.py install
test_script:
- cmd: >-
    %CONDA_PREFIX%\python.exe -m unittest unit_test

    %CONDA_PREFIX%\python.exe example_pf.py
